# Generated by Django 5.1.1 on 2024-09-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('HR', 'Human Resource'), ('IT', 'Information Technology'), ('Marketing', 'Marketing'), ('Finance', 'Finance'), ('R&D', 'Research and Development')], max_length=50)),
                ('salary', models.IntegerField()),
                ('location', models.CharField(choices=[('Nairobi, Kenya', 'Nairobi, Kenya'), ('California, US', 'California, US'), ('London, UK', 'London, UK'), ('San fransisco, US', 'San fransisco, US'), ('Cape Town, SA', 'Cape Town, SA')], max_length=100)),
                ('introduction', models.CharField(max_length=220)),
                ('brief_posting_description', models.CharField(max_length=400)),
                ('responsibilities', models.CharField(max_length=3000)),
                ('qualifications', models.CharField(max_length=1500)),
                ('is_active', models.BooleanField(default=True)),
                ('date_posted', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
