# Generated by Django 5.1.1 on 2024-09-30 07:15

import HumanResource.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Prefer not to say', 'Prefer not to say')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(choices=[('Nairobi, Kenya', 'Nairobi, Kenya'), ('California, US', 'California, US'), ('London, UK', 'London, UK'), ('San fransisco, US', 'San fransisco, US'), ('Cape Town, SA', 'Cape Town, SA')], max_length=100)),
                ('cv', models.FileField(upload_to='cvs/', validators=[HumanResource.models.validate_pdf])),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='HumanResource.job')),
            ],
        ),
    ]
